name: Poll API Every 5 Minutes

on:
  schedule:
    # Runs every 5 minutes, offset from the top of the hour to avoid queues
    - cron: '3,8,13,18,23,28,33,38,43,48,53,58 * * * *'

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    steps:
      - name: Send API Request
        run: |
          curl -X GET "https://rohanchauhan.me/"
